-- -- Turn on transparency
-- return {
--     "tokyonight.nvim",
--     opts = {
--         transparent = true,
--         styles = {
--             sidebars = "transparent",
--             floats = "transparent",
--         },
--     },
-- }
-- Turn off transparency
return {}
